import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Menu from "./components/menu";

export const metadata: Metadata = {
  title: "Erick Araujo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-mono antialiased`}>
        <Header>
          <Menu />
        </Header>
        {children}
      </body>
    </html>
  );
}
